### PR TITLE
Fix link to updated docs about NEWS entries

### PR DESCRIPTION
**Pull request by techtonik**
See https://github.com/pypa/pip/issues/5753

### CODE REVIEW

**Comment by pradyunsg** [comment]
IIUC, this change needs to be made on the `twisted` branch.

**Comment by pradyunsg** [comment]
Closing since I made the change to the `twisted` branch myself.

**Comment by pradyunsg** [comment]
Thanks for the PR @techtonik!

**Comment by techtonik** [comment]
No problem. Glad it worked. =)

**Pull request closed without merging**
