### PR TITLE
Add license file

### PR DESCRIPTION
**Pull request by Mariatta**
Using Apache License 2.0 template provided by GitHub

### CODE REVIEW

**Comment by pradyunsg** [comment]
No, I'm not.

**Comment by techtonik** [comment]
And who besides @dstufft can do this?

**Comment by techtonik** [comment]
@pradyunsg headers for Apache 2.0 license are already in present in source files and added by @dstufft https://github.com/pypa/browntruck/blame/master/browntruck/__init__.py so there is no need to distract him from more precious PRs.

**Comment by pradyunsg** [comment]
Fair enough. :)

**Comment by pradyunsg** [comment]
Thanks @Mariatta and @techtonik. ^>^

**Comment by techtonik** [comment]
That's impressive. :D

**Pull request merged**
